services:
  app:
    build: .
    ports:
      - "2345:2345"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.example
    volumes:
      - ./migrations:/app/migrations
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=ksimouse
      - DB_PASSWORD=kamilfocusup
      - DB_NAME=focusup_db
      - JWT_SECRET=ksimousefocusdbup
      - APP_PORT=2345

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - focusup_db_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  focusup_db_data: